import sys
import os
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QListWidget, QPushButton,
    QGroupBox, QTextEdit, QScrollArea, QStackedWidget, QMessageBox
)
from PySide6.QtGui import QPixmap
from PySide6.QtCore import Qt

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import reporting # To access reporting.REPORTS_DIR

REPORTS_DIR_GUI = reporting.REPORTS_DIR

class ReportViewerTab(QWidget):
    def __init__(self):
        super().__init__()
        self.main_layout = QHBoxLayout(self)

        # Left Panel: Report Files List
        left_panel_layout = QVBoxLayout()
        left_panel_group = QGroupBox("报告文件列表 (Report Files)")

        self.reports_list_widget = QListWidget()
        self.reports_list_widget.currentItemChanged.connect(self.display_selected_report)
        left_panel_layout.addWidget(self.reports_list_widget)

        self.refresh_reports_button = QPushButton("刷新报告列表 (Refresh Report List)")
        self.refresh_reports_button.clicked.connect(self.populate_reports_list)
        left_panel_layout.addWidget(self.refresh_reports_button)

        left_panel_group.setLayout(left_panel_layout)
        self.main_layout.addWidget(left_panel_group, 1) # Stretch factor 1

        # Right Panel: Viewer Area
        right_panel_group = QGroupBox("报告内容 (Report Content)")
        right_panel_layout = QVBoxLayout() # Use QVBoxLayout for the group box

        self.viewer_stack = QStackedWidget()

        # Text Viewer
        self.text_report_viewer = QTextEdit()
        self.text_report_viewer.setReadOnly(True)
        self.viewer_stack.addWidget(self.text_report_viewer) # Index 0

        # Image Viewer
        self.image_viewer_scroll_area = QScrollArea()
        self.image_viewer_scroll_area.setWidgetResizable(True)
        self.image_report_label = QLabel("选择图片报告以查看 (Select an image report to view)")
        self.image_report_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_report_label.setMinimumSize(400,300) # Give it a minimum size
        self.image_viewer_scroll_area.setWidget(self.image_report_label)
        self.viewer_stack.addWidget(self.image_viewer_scroll_area) # Index 1

        right_panel_layout.addWidget(self.viewer_stack)
        right_panel_group.setLayout(right_panel_layout)
        self.main_layout.addWidget(right_panel_group, 3) # Stretch factor 3 for viewer

        self.populate_reports_list()
        # Set initial view (e.g., text viewer with a message if no file selected)
        self.text_report_viewer.setText("请从左侧列表中选择一个报告文件进行查看。\n(Please select a report file from the list on the left to view.)")
        self.viewer_stack.setCurrentWidget(self.text_report_viewer)


    def populate_reports_list(self):
        self.reports_list_widget.clear()
        if not os.path.exists(REPORTS_DIR_GUI):
            # Try to create it if it doesn't exist, as reports are generated by other tabs
            try:
                os.makedirs(REPORTS_DIR_GUI)
                print(f"Created reports directory: {REPORTS_DIR_GUI}")
            except Exception as e:
                QMessageBox.warning(self, "目录错误 (Directory Error)",
                                    f"报告目录 '{REPORTS_DIR_GUI}' 不存在且无法创建 (Report directory does not exist and could not be created): {e}")
                self.reports_list_widget.addItem("报告目录未找到 (Reports directory not found)")
                self.reports_list_widget.setEnabled(False)
                return

        self.reports_list_widget.setEnabled(True)
        try:
            files = [f for f in os.listdir(REPORTS_DIR_GUI) if f.endswith(".txt") or f.endswith(".png")]
            if not files:
                self.reports_list_widget.addItem("无报告文件 (No report files)")
            else:
                self.reports_list_widget.addItems(files)
        except Exception as e:
            QMessageBox.critical(self, "错误 (Error)", f"无法列出报告文件 (Could not list report files): {e}")


    def display_selected_report(self, current_item):
        if not current_item:
            self.text_report_viewer.setText("请选择一个报告文件。(Please select a report file.)")
            self.image_report_label.setText("选择图片报告以查看。(Select an image report to view.)")
            self.image_report_label.setPixmap(QPixmap()) # Clear image
            self.viewer_stack.setCurrentWidget(self.text_report_viewer) # Default to text viewer
            return

        filename = current_item.text()
        full_path = os.path.join(REPORTS_DIR_GUI, filename)

        if not os.path.exists(full_path):
            QMessageBox.warning(self, "文件错误 (File Error)", f"文件 '{filename}' 未找到 (File not found).")
            self.text_report_viewer.setText(f"文件 '{filename}' 未找到。")
            self.image_report_label.setText(f"文件 '{filename}' 未找到。")
            self.image_report_label.setPixmap(QPixmap())
            return

        try:
            if filename.endswith(".txt"):
                with open(full_path, 'r', encoding='utf-8') as f:
                    self.text_report_viewer.setText(f.read())
                self.viewer_stack.setCurrentWidget(self.text_report_viewer)
            elif filename.endswith(".png"):
                pixmap = QPixmap(full_path)
                if pixmap.isNull():
                    self.image_report_label.setText(f"无法加载图片 '{filename}' (Could not load image).")
                    QMessageBox.warning(self, "图片错误 (Image Error)", f"无法加载图片文件 '{filename}'.")
                else:
                    self.image_report_label.setPixmap(pixmap.scaled(
                        self.image_report_label.size(), # Scale to label size
                        Qt.AspectRatioMode.KeepAspectRatio,
                        Qt.TransformationMode.SmoothTransformation
                    ))
                self.viewer_stack.setCurrentWidget(self.image_viewer_scroll_area)
            else:
                self.text_report_viewer.setText(f"不支持的文件类型: {filename}\n(Unsupported file type.)")
                self.viewer_stack.setCurrentWidget(self.text_report_viewer)

        except Exception as e:
            QMessageBox.critical(self, "打开文件错误 (File Open Error)", f"无法打开或读取文件 (Could not open/read file) '{filename}': {e}")
            self.text_report_viewer.setText(f"打开文件 '{filename}' 时出错: {e}")
            self.viewer_stack.setCurrentWidget(self.text_report_viewer)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # Ensure reports directory exists for standalone test
    if not os.path.exists(REPORTS_DIR_GUI):
        os.makedirs(REPORTS_DIR_GUI)
        print(f"Created directory: {REPORTS_DIR_GUI} for demo.")
        # Create dummy files for testing
        try:
            with open(os.path.join(REPORTS_DIR_GUI, "dummy_report.txt"), 'w') as f:
                f.write("This is a dummy text report.\nLine 2.")
            # For a dummy PNG, it's harder. We'll rely on other tabs generating actual PNGs.
            # Or, create a tiny valid PNG if really needed for standalone test.
            # For now, a missing PNG will be handled by the display logic.
            print("Created dummy_report.txt. Dummy PNG not created for this simple test.")
        except Exception as e:
            print(f"Could not create dummy test files: {e}")

    main_widget = ReportViewerTab()
    main_widget.setWindowTitle("Report Viewer Tab Test")
    main_widget.setGeometry(100, 100, 800, 600)
    main_widget.show()
    sys.exit(app.exec())
